### ISSUE TITLE
Add database plugin

### ISSUE THREAD

**Issue by poirierlouis** [tiltedphoques/CyberpunkMP#28]
This is to continue on conversation https://github.com/tiltedphoques/CyberpunkMP/issues/21#issuecomment-2498318868

Could it be created as a facade, such as only one plugin API (Database) is used by other plugins. But actual implementation of the database would be separate plugins like PostgresDatabase, MongoDatabase?
Maybe it would require two facades, one for NoSQL and another for SQL.

wdyt?

**Comment by maximegmd** [comment]
I don't think we need a database plugin. Plugins that need a DB can easily interface with whatever database they want by just importing existing libs.

**Comment by maximegmd** [comment]
See: https://learn.microsoft.com/en-us/ef/core/get-started/overview/first-app?tabs=netcore-cli

**Comment by poirierlouis** [comment]
Hum I see, this Entity Framework Core is nice. So basically, server owners would handle storage of stats/inventory/etc. themself instead of providing a common ground through a plugin?

**Comment by maximegmd** [comment]
Yes, persistence isn't the goal of the base framework, this can be handled by plugins.
