### ISSUE TITLE
Noticable server CPU usage on idle

### ISSUE THREAD

**Issue by Zhincore** [tiltedphoques/CyberpunkMP#31]
Even when idle for a long time, the server still consumes CPU. 
It's probably running the game server loop unconditionally.

**Expected behavior:**
The server should *"sleep"* when there are no players connected.

**Comment by maximegmd** [comment]
Fixed by [69aa6d5](https://github.com/tiltedphoques/CyberpunkMP/commit/69aa6d557992e05b122f3decbdd925db02d37c25)
