### ISSUE TITLE
[Plugin] Provide common ground with an abstract AManager class 

### ISSUE THREAD

**Issue by poirierlouis** [tiltedphoques/CyberpunkMP#39]
Provide a common ground for plugins to implement their manager with logger and join/leave features.

It could be:
```cs
using CyberpunkSdk;
using CyberpunkSdk.Systems;

abstract class AManager
{
    protected readonly Logger _logger;
    protected readonly List<ulong> _players = [];

    protected AManager()
    {
        _logger = new Logger(GetType().Name[..^"Manager".Length]);

        Server.PlayerSystem.PlayerJoinEvent += OnPlayerJoin;
        Server.PlayerSystem.PlayerLeftEvent += OnPlayerLeave;
    }

    protected void OnPlayerJoin(ulong id)
    {
        _players.Add(id);
        _logger.Debug($"Player {id} joined");
    }

    protected void OnPlayerLeave(ulong id)
    {
        _players.Remove(id);
        _logger.Debug($"Player {id} left");
    }
}
```

Example of usage:
```cs
// ...

internal MyManager : AManager
{
    internal MyManager()
    {
        Server.Timer.Add(OnTimer, 300.0f);
    }

    protected override void OnPlayerJoin(ulong id)
    {
        base.OnPlayerJoin(id);
    }

    protected override void OnPlayerLeave(ulong id)
    {
        base.OnPlayerLeave(id);
    }
    
    // ...
}
```

While it is not much, I think it would be more straightforward when starting a new plugin.
I was also thinking about defining some `using PlayerId = ulong`. Code would be easier to read and keep track of what it is what...

AManager could introduce a template to store `<id>` + `<object>` per player in a Map instead of List. With some premade helpers to add/remove entries.

wdyt?

**Comment by maximegmd** [comment]
You can already access a list of players through:

```csharp
Server.PlayerSystem.PlayerIds;
```

I don't understand the use case of this base manager, wouldn't it lead to data duplication and log spam?

**Comment by poirierlouis** [comment]
For logging, Debug is used in example. So server logging level can be configured to Info in production.
Hmm, could be handy for beginners I guess. Only override methods when you want to implement logic on join/leave event. Otherwise experts can always just write their own manager and implement it all.

Or we could just write an example in MP wiki when it is online.
